{{- range $svcName, $svc := .Values.services }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ztd.svcFullname" (dict "root" $ "service" $svcName) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ztd.serviceLabels" (dict "root" $ "service" $svcName) | nindent 4 }}
automountServiceAccountToken: false
---
{{- end }}
