{{- range $svcName, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ztd.svcName" (dict "service" $svcName) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ztd.serviceLabels" (dict "root" $ "service" $svcName) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ztd.serviceSelectorLabels" (dict "root" $ "service" $svcName) | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
{{- end }}
