# Phase 6: deploy the ztd-capstone app chart (Phase 3) + its Postgres
# credentials Secret into the pre-existing `dev` namespace
# (kubernetes_namespace.this["dev"], created in Phase 4). Pods land on the
# dedicated platform nodegroup via the chart's own nodeSelector — nothing
# here touches the ng-dense nodegroup or any other namespace.

# ---------------------------------------------------------------------------
# Postgres credentials — generated by Terraform, stored only in a
# Kubernetes Secret (never committed to git). Consumed by the chart's
# postgres StatefulSet (POSTGRES_PASSWORD) and the orders service
# (DATABASE_URL) via secretKeyRef.
# ---------------------------------------------------------------------------

resource "random_password" "postgres" {
  length  = 20
  special = false
}

resource "kubernetes_secret" "postgres" {
  metadata {
    name      = "ztd-capstone-postgres"
    namespace = kubernetes_namespace.this["dev"].metadata[0].name
  }

  data = {
    postgres-password = random_password.postgres.result
    database-url      = "postgresql://ztd:${random_password.postgres.result}@postgres:5432/ztd"
  }

  type = "Opaque"
}

# ---------------------------------------------------------------------------
# ztd-capstone app chart (Phase 3) — frontend, api-gateway, orders, catalog
# + postgres StatefulSet, into dev. depends_on the Secret (so DATABASE_URL /
# postgres-password exist before pods reference them) and the
# kube-prometheus-stack release (so the ServiceMonitor CRD exists before the
# chart's servicemonitor.yaml templates are applied).
# ---------------------------------------------------------------------------

resource "helm_release" "app" {
  count = var.app_deploy_enabled ? 1 : 0

  name      = "ztd-capstone"
  chart     = "${path.module}/../../deploy/helm/ztd-capstone"
  namespace = kubernetes_namespace.this["dev"].metadata[0].name
  timeout   = 600

  values = [
    file("${path.module}/../../deploy/helm/ztd-capstone/values.yaml"),
    file("${path.module}/../../deploy/helm/ztd-capstone/values-dev.yaml"),
  ]

  set {
    name  = "image.tag"
    value = var.app_image_tag
  }

  depends_on = [
    kubernetes_secret.postgres,
    helm_release.kube_prometheus_stack,
  ]
}
