# Phase 6/8: Postgres credentials Secret for the ztd-capstone app chart, in
# the pre-existing `dev` namespace (kubernetes_namespace.this["dev"],
# created in Phase 4). Terraform keeps owning this Secret (random_password,
# never committed to git) — the app chart itself (frontend, api-gateway,
# orders, catalog, postgres StatefulSet) is now deployed by ArgoCD
# (deploy/argocd/apps/dev.yaml, argocd.tf) from git, not by Terraform.
# `helm_release.app` (Phase 6) was removed here as part of the Phase 8
# ArgoCD cutover — nothing here touches the ng-dense nodegroup or any other
# namespace.

# ---------------------------------------------------------------------------
# Postgres credentials — generated by Terraform, stored only in a
# Kubernetes Secret (never committed to git). Consumed by the chart's
# postgres StatefulSet (POSTGRES_PASSWORD) and the orders service
# (DATABASE_URL) via secretKeyRef.
# ---------------------------------------------------------------------------

resource "random_password" "postgres" {
  length  = 20
  special = false
}

resource "kubernetes_secret" "postgres" {
  metadata {
    name      = "ztd-capstone-postgres"
    namespace = kubernetes_namespace.this["dev"].metadata[0].name
  }

  data = {
    postgres-password = random_password.postgres.result
    database-url      = "postgresql://ztd:${random_password.postgres.result}@postgres:5432/ztd"
  }

  type = "Opaque"
}
