# Phase 5 observability stack: Prometheus/Grafana (kube-prometheus-stack),
# Loki + Promtail (logs), Tempo + OpenTelemetry Collector (traces).
#
# Everything installs into the pre-existing `observability` namespace
# (kubernetes_namespace.this["observability"], created in Phase 4) and is
# pinned to the dedicated platform nodegroup via each chart's own values
# file under deploy/observability/. Nothing here touches any other
# namespace or the pre-existing ng-dense nodegroup.

# ---------------------------------------------------------------------------
# Grafana admin credentials - generated by Terraform, stored only in a
# Kubernetes Secret (never committed to git).
# ---------------------------------------------------------------------------

resource "random_password" "grafana_admin" {
  length  = 24
  special = false
}

resource "kubernetes_secret" "grafana_admin" {
  metadata {
    name      = "grafana-admin"
    namespace = kubernetes_namespace.this["observability"].metadata[0].name
  }

  data = {
    admin-user     = "admin"
    admin-password = random_password.grafana_admin.result
  }

  type = "Opaque"
}

# ---------------------------------------------------------------------------
# Task 1: kube-prometheus-stack (Prometheus Operator + Prometheus + Grafana +
# node-exporter + kube-state-metrics)
# ---------------------------------------------------------------------------

resource "helm_release" "kube_prometheus_stack" {
  name       = "kube-prometheus-stack"
  repository = "https://prometheus-community.github.io/helm-charts"
  chart      = "kube-prometheus-stack"
  version    = "87.12.1"
  namespace  = kubernetes_namespace.this["observability"].metadata[0].name
  timeout    = 900

  values = [file("${path.module}/../../deploy/observability/kube-prometheus-stack.values.yaml")]

  depends_on = [kubernetes_secret.grafana_admin]
}

# ---------------------------------------------------------------------------
# Task 2: Loki + Promtail (logs)
# ---------------------------------------------------------------------------

resource "helm_release" "loki" {
  name       = "loki"
  repository = "https://grafana.github.io/helm-charts"
  chart      = "loki"
  version    = "6.55.0"
  namespace  = kubernetes_namespace.this["observability"].metadata[0].name
  timeout    = 600

  values = [file("${path.module}/../../deploy/observability/loki.values.yaml")]
}

resource "helm_release" "promtail" {
  name       = "promtail"
  repository = "https://grafana.github.io/helm-charts"
  chart      = "promtail"
  version    = "6.17.1"
  namespace  = kubernetes_namespace.this["observability"].metadata[0].name
  timeout    = 300

  values = [file("${path.module}/../../deploy/observability/promtail.values.yaml")]

  depends_on = [helm_release.loki]
}

# ---------------------------------------------------------------------------
# Task 3: Tempo + OpenTelemetry Collector (traces)
# ---------------------------------------------------------------------------

resource "helm_release" "tempo" {
  name       = "tempo"
  repository = "https://grafana.github.io/helm-charts"
  chart      = "tempo"
  version    = "1.24.4"
  namespace  = kubernetes_namespace.this["observability"].metadata[0].name
  timeout    = 300

  values = [file("${path.module}/../../deploy/observability/tempo.values.yaml")]
}

resource "helm_release" "otel_collector" {
  name       = "opentelemetry-collector"
  repository = "https://open-telemetry.github.io/opentelemetry-helm-charts"
  chart      = "opentelemetry-collector"
  version    = "0.164.1"
  namespace  = kubernetes_namespace.this["observability"].metadata[0].name
  timeout    = 300

  values = [file("${path.module}/../../deploy/observability/opentelemetry-collector.values.yaml")]

  depends_on = [helm_release.tempo]
}

# ---------------------------------------------------------------------------
# Task 4: Grafana dashboards, committed as JSON and provisioned via the
# kube-prometheus-stack dashboard sidecar (label grafana_dashboard=1).
# ---------------------------------------------------------------------------

locals {
  dashboard_files = {
    service-red     = "service-red.json"
    logs-overview   = "logs-overview.json"
    traces-overview = "traces-overview.json"
    cluster-health  = "cluster-health.json"
  }
}

resource "kubernetes_config_map" "grafana_dashboards" {
  for_each = local.dashboard_files

  metadata {
    name      = "grafana-dashboard-${each.key}"
    namespace = kubernetes_namespace.this["observability"].metadata[0].name
    labels = {
      grafana_dashboard = "1"
    }
  }

  data = {
    (each.value) = file("${path.module}/../../deploy/observability/dashboards/${each.value}")
  }

  depends_on = [helm_release.kube_prometheus_stack]
}
